# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 599)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chArt_Btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chArt_Btn.sizePolicy().hasHeightForWidth())
        self.chArt_Btn.setSizePolicy(sizePolicy)
        self.chArt_Btn.setObjectName("chArt_Btn")
        self.horizontalLayout.addWidget(self.chArt_Btn)
        self.testToggle = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testToggle.sizePolicy().hasHeightForWidth())
        self.testToggle.setSizePolicy(sizePolicy)
        self.testToggle.setObjectName("testToggle")
        self.horizontalLayout.addWidget(self.testToggle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.remLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.remLabel.setFont(font)
        self.remLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.remLabel.setObjectName("remLabel")
        self.horizontalLayout.addWidget(self.remLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.timeLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout.addWidget(self.timeLabel)
        self.timeCombo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeCombo.sizePolicy().hasHeightForWidth())
        self.timeCombo.setSizePolicy(sizePolicy)
        self.timeCombo.setMinimumSize(QtCore.QSize(90, 0))
        self.timeCombo.setEditable(False)
        self.timeCombo.setObjectName("timeCombo")
        self.timeCombo.addItem("")
        self.timeCombo.addItem("")
        self.timeCombo.addItem("")
        self.timeCombo.addItem("")
        self.timeCombo.addItem("")
        self.timeCombo.addItem("")
        self.timeCombo.addItem("")
        self.timeCombo.addItem("")
        self.timeCombo.addItem("")
        self.horizontalLayout.addWidget(self.timeCombo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.artListView = QtWidgets.QListView(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(20)
        self.artListView.setFont(font)
        self.artListView.setObjectName("artListView")
        self.verticalLayout.addWidget(self.artListView)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(20)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.timeCombo.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chinese Typing PyQt v1.2"))
        self.chArt_Btn.setText(_translate("MainWindow", "選擇文章..."))
        self.testToggle.setText(_translate("MainWindow", "開始測驗"))
        self.remLabel.setText(_translate("MainWindow", "10:00"))
        self.timeLabel.setText(_translate("MainWindow", "測驗時間"))
        self.timeCombo.setCurrentText(_translate("MainWindow", "10分鐘"))
        self.timeCombo.setItemText(0, _translate("MainWindow", "1分鐘"))
        self.timeCombo.setItemText(1, _translate("MainWindow", "3分鐘"))
        self.timeCombo.setItemText(2, _translate("MainWindow", "5分鐘"))
        self.timeCombo.setItemText(3, _translate("MainWindow", "8分鐘"))
        self.timeCombo.setItemText(4, _translate("MainWindow", "10分鐘"))
        self.timeCombo.setItemText(5, _translate("MainWindow", "15分鐘"))
        self.timeCombo.setItemText(6, _translate("MainWindow", "20分鐘"))
        self.timeCombo.setItemText(7, _translate("MainWindow", "25分鐘"))
        self.timeCombo.setItemText(8, _translate("MainWindow", "30分鐘"))

